# https://github.com/marketplace/actions/setup-pnpm#use-cache-to-reduce-installation-time
name: "Install dependencies"
description: "Setup pnpm and install project dependencies"
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: 10
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: "pnpm"

    # Set up .npmrc to fetch packages published on GitHub Packages.
    - name: Creating .npmrc
      run: |
        cat << EOF > "$HOME/.npmrc"
          //registry.npmjs.org/:_authToken=$NPM_TOKEN
        EOF
      env:
        NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
