# https://www.chromatic.com/docs/github-actions/#workflow-setup
name: "Chromatic"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Publish core package to Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          # https://www.chromatic.com/docs/turbosnap#configure
          onlyChanged: true
          workingDir: packages/core
