name: "Verify code quality"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    permissions:
      pull-requests: write
      checks: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Run tests
        run: pnpm core run ci:test
      - name: "Report Coverage"
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          working-directory: packages/core
      # Generate coverage badge and push it to the `badges` branch. These two
      # steps are only run on the `main` branch.
      - name: Publish Results Badge
        uses: wjervis7/vitest-badge-action@v1.0.0
        # if: github.ref == 'refs/heads/main' && (success() || failure())
        with:
          result-type: statements
          upload-badge: false
          vitest-config-path: packages/core/vitest.config.js
          summary-path: packages/core/coverage/coverage-summary.json
      - name: Commit coverage badge
        uses: stefanzweifel/git-auto-commit-action@v4
        # if: github.ref == 'refs/heads/main'
        with:
          commit_message: "Update coverage badge"
          file_pattern: "./badge.svg"
          create_branch: true
          branch: badges
          # status_options: "--untracked-files=normal"
          # add_options: "--all"
          push_options: "--force"

  verify-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Lint code
        run: pnpm run lint
      - name: Verify code formatting
        run: pnpm run format:check
      - name: Check for dependency duplication
        run: pnpm dedupe --check
