name: "Verify code quality"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    permissions:
      pull-requests: write
      checks: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Run tests
        run: pnpm core run ci:test
      - name: "Report Coverage"
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          working-directory: packages/core
      - name: Publish Results Badge
        uses: wjervis7/vitest-badge-action@v1.0.0
        if: github.ref == 'refs/heads/main' && (success() || failure())
        with:
          summary-path: packages/core/coverage/coverage-summary.json
          result-type: statements
          upload-badge: false
      - name: Commit coverage badge
        uses: stefanzweifel/git-auto-commit-action@v4
        if: github.ref == 'refs/heads/main'
        with:
          commit-message: "Update coverage badges"
          create_branch: true
          branch: badges
          file_pattern: "./badge.svg"

  verify-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Lint code
        run: pnpm run lint
      - name: Verify code formatting
        run: pnpm run format:check
      - name: Check for dependency duplication
        run: pnpm dedupe --check
